-- Superusers can inspect the complete operational history without changing
-- the existing administrator login flow.
alter table public.users add column if not exists is_superuser boolean not null default false;
update public.users set is_superuser = true where lower(username) = 'admin' and role = 'admin';

-- Coupons are archived instead of physically removed. Regular operational
-- queries filter these rows; the supervision panel keeps them visible.
alter table public.coupons add column if not exists deleted_at timestamptz;
alter table public.coupons add column if not exists deleted_by bigint references public.users(id) on delete set null;
create index if not exists coupons_deleted_at_idx on public.coupons(deleted_at);

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  username text not null,
  role text not null,
  session_token_hash text not null unique,
  signed_in_at timestamptz not null default now(),
  signed_out_at timestamptz
);
create index if not exists login_events_signed_in_at_idx on public.login_events(signed_in_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id) on delete set null,
  actor_username text,
  action text not null,
  entity_type text not null,
  entity_id text,
  details text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists audit_events_created_at_idx on public.audit_events(created_at desc);

alter table public.login_events enable row level security;
alter table public.audit_events enable row level security;
revoke all on public.login_events, public.audit_events from anon, authenticated;
