create table public.business_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table public.races (
  id text primary key,
  name text not null,
  short_name text not null,
  coupon_quantity integer not null check (coupon_quantity between 1 and 10000),
  start_date date not null,
  validity_days integer not null check (validity_days between 1 and 365),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  description text not null default '',
  logo_path text,
  card_image_path text,
  card_image_position text not null default 'center'
);

create table public.site_content (
  content_key text primary key,
  content jsonb not null,
  updated_at timestamptz not null default now()
);

create table public.coupon_rules (
  id bigint generated by default as identity primary key,
  body text not null,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table public.businesses (
  id text primary key,
  name text not null,
  category text not null references public.business_categories(name) on update cascade on delete restrict,
  municipality text not null check (municipality in ('Valverde', 'La Frontera', 'El Pinar')),
  area text not null default '',
  phone text not null default '',
  address text not null default '',
  lat double precision not null check (lat between 27.59 and 27.86),
  lng double precision not null check (lng between -18.26 and -17.82),
  opening_hours text not null default '',
  description text not null default '',
  image text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coupons (
  code text primary key check (code ~ '^EH-(BES|BIM|MER)-[A-HJ-KM-NP-Z][1-9][A-HJ-KM-NP-Z][1-9]{3}[A-HJ-KM-NP-Z]$'),
  race_id text not null references public.races(id) on update cascade on delete restrict,
  business_id text not null references public.businesses(id) on update cascade on delete restrict,
  amount_cents integer not null check (amount_cents > 0),
  used_cents integer not null default 0 check (used_cents between 0 and amount_cents),
  created_at timestamptz not null default now()
);
create index coupons_race_id_idx on public.coupons(race_id);
create index coupons_business_id_idx on public.coupons(business_id);

create table public.redemptions (
  id bigint generated by default as identity primary key,
  code text not null references public.coupons(code) on update cascade on delete restrict,
  business_id text not null references public.businesses(id) on update cascade on delete restrict,
  amount_cents integer not null check (amount_cents > 0),
  balance_after_cents integer not null check (balance_after_cents >= 0),
  created_at timestamptz not null default now()
);
create index redemptions_code_created_at_idx on public.redemptions(code, created_at desc, id desc);
create index redemptions_business_created_at_idx on public.redemptions(business_id, created_at desc, id desc);

create table public.users (
  id bigint generated by default as identity primary key,
  username text not null,
  password_hash text not null,
  role text not null check (role in ('admin', 'merchant')),
  business_id text unique references public.businesses(id) on update cascade on delete restrict,
  demo_business_id text references public.businesses(id) on update cascade on delete set null,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  first_name text,
  last_name text,
  email text,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  constraint users_business_role_check check ((role = 'merchant' and business_id is not null and demo_business_id is null) or (role = 'admin' and business_id is null))
);
create unique index users_username_lower_unique on public.users (lower(username));
create unique index users_email_lower_unique on public.users (lower(email)) where email is not null;
create index users_demo_business_id_idx on public.users(demo_business_id);

create table public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index sessions_user_id_idx on public.sessions(user_id);
create index sessions_expires_at_idx on public.sessions(expires_at);

create table public.geocoding_cache (
  cache_key text primary key,
  lat double precision not null check (lat between 27.59 and 27.86),
  lng double precision not null check (lng between -18.26 and -17.82),
  updated_at timestamptz not null default now()
);

create table public.public_lookup_limits (
  identifier_hash text primary key,
  window_started_at timestamptz not null,
  attempt_count integer not null check (attempt_count >= 0),
  updated_at timestamptz not null default now()
);
create index public_lookup_limits_updated_at_idx on public.public_lookup_limits(updated_at);

create function public.consume_coupon_lookup(p_identifier_hash text, p_now timestamptz default now())
returns table (allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_count integer;
  current_window timestamptz;
begin
  insert into public.public_lookup_limits as limits (identifier_hash, window_started_at, attempt_count, updated_at)
  values (p_identifier_hash, p_now, 1, p_now)
  on conflict (identifier_hash) do update
    set window_started_at = case
          when limits.window_started_at <= p_now - interval '15 minutes' then p_now
          else limits.window_started_at
        end,
        attempt_count = case
          when limits.window_started_at <= p_now - interval '15 minutes' then 1
          when limits.attempt_count >= 10 then limits.attempt_count
          else limits.attempt_count + 1
        end,
        updated_at = p_now
  returning limits.attempt_count, limits.window_started_at
  into current_count, current_window;

  return query select
    current_count <= 10,
    case when current_count <= 10 then 0 else greatest(1, ceil(extract(epoch from (current_window + interval '15 minutes' - p_now))::numeric)::integer) end;
end;
$$;
revoke all on function public.consume_coupon_lookup(text, timestamptz) from public, anon, authenticated;

alter table public.business_categories enable row level security;
alter table public.races enable row level security;
alter table public.site_content enable row level security;
alter table public.coupon_rules enable row level security;
alter table public.businesses enable row level security;
alter table public.coupons enable row level security;
alter table public.redemptions enable row level security;
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.geocoding_cache enable row level security;
alter table public.public_lookup_limits enable row level security;

-- The application server connects using a private database role. No browser or
-- anonymous Supabase role receives table access or lookup-function execution.
